druid.host=druid-coordinator
druid.plaintextPort=8081
druid.service=druid/coordinator
druid.coordinator.asOverlord.enabled=true
druid.coordinator.asOverlord.overlordService=druid/overlord
druid.indexer.runner.type=remote