druid.host=druid-router
druid.plaintextPort=8888
druid.service=druid/router
druid.router.defaultBrokerServiceName=druid/broker
druid.router.coordinatorServiceName=druid/coordinator
druid.router.managementProxy.enabled=true